### ISSUE TITLE
Getting error while exporting file as XML

### ISSUE THREAD

**Issue by anindha-dhar** [mitsuba-renderer/mitsuba-blender#82]
Getting error while exporting file as XML
After doing the word, while I was trying to export the file as XML I' getting the following error:

```
Python: Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mitsuba-blender\io\__init__.py", line 136, in execute
    self.converter.scene_to_dict(deps_graph, window_manager)
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mitsuba-blender\io\exporter\__init__.py", line 97, in scene_to_dict
    geometry.export_object(object_instance, self.export_ctx, evaluated_obj.name in particles)
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mitsuba-blender\io\exporter\geometry.py", line 131, in export_object
    mts_mesh.write_ply(filepath)
AttributeError: 'NoneType' object has no attribute 'write_ply'
```

![image](https://github.com/mitsuba-renderer/mitsuba-blender/assets/66663552/f6cef90c-d882-48a5-b9e9-f3ca45509c16)

**To Reproduce**
1. Go to 'File'
2. Click on 'Export'
3. Scroll down to 'Mitsuba(.xml)'

**Environment (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 3.4
 - Add-on Version: Latest

**Additional context**
I was trying to do my work on Blender 4.0. But I faced difficulties while adding the addon. After reading the issues, I downgraded to version 3.4 and successfully add the addon. But after completing my word I got the error while exporting.

**Comment by bathal1** [comment]
This should now be fixed with the latest release of the add-on. Please upgrade and re-open this issue if the problem persists.
